### ISSUE TITLE
Dependencies in ext_emconf.php are not set

### ISSUE THREAD

**Issue by rabe69** [lochmueller/calendarize_news#1]
Because of the missing dependencies to "calendarize" and "news", the backend crashes after deinstalling calendarize at first.

**Comment by lochmueller** [comment]
This is a problem of the TER. There are vali dependencies, but if a EXT is downloaded via TER website, the dependencies are deleted by the TER process. 

https://github.com/lochmueller/calendarize_news/blob/master/ext_emconf.php

I close this issue...
