### ISSUE TITLE
Fatal error after installing new version 4.1.0

### ISSUE THREAD

**Issue by angeloprevitali** [lochmueller/calendarize_news#10]
Hi Tim

thanks for adapting your EXT:calendarize_news :)

If I install your revised extension i got an fatal error in the **backend** of my TYPO3 with the following message:

Fatal error: Uncaught Doctrine\DBAL\Driver\Mysqli\MysqliException: Unknown column 'uid' in 'where clause' in /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php:94 Stack trace: #0 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php(120): Doctrine\DBAL\Driver\Mysqli\MysqliStatement->__construct(Object(mysqli), 'SELECT * FROM `...') #1 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(844): Doctrine\DBAL\Driver\Mysqli\MysqliConnection->prepare('SELECT * FROM `...') #2 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(206): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM `...', Array, Array) #3 /typo3/sysext/core/Classes/Database/Query/QueryBuilder.php(187): Doctrine\DBAL\Query\QueryBuilder->execute() #4 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 71 

Any hint?

I do use

TYPO3 version 8.7.23
Composer: No
OS: Linux
PHP version 7.2

EXT:calendarize_news version 4.1.0
EXT:news version 7.1.0
EXT:eventnews (of Georg Ringer) version 3.0.0

Even if i uninstall the EXT:eventnews the error occures. It happens immediately after installing the extension. As soon I click on the Web > Calendarize icon the error occures. If I want to add the plug-In for configure it the whole page can not be opened due to the error. So I got to uninstall the extension to have a chance to edit the page in the be. In the frontend the same error ocures, too.

Best regards,
Angelo

**Comment by angeloprevitali** [comment]
I just found out why the error occures: The problem is that just on this extension (or maybe a dependency of this) does NOT updates the database. I had the same problem some months ago with your extension, too.
How can that be possible that just your extension does not updates the database correctly after installing the extension? For me a mistery. All other extensions updates their databases corretly. It is just yours... Any hint?

**Comment by lochmueller** [comment]
The reason would be, that the extension ist EXT:autoloader based. That means the SQL is generated "on-the-fly" and the Extension use two hooks (one in the install tool and one in the installation process) to create the right tables. I don't know why this mechanism do not work in you installation. I will close this issue... feel free to create in issue here: https://github.com/lochmueller/autoloader/issues (Please add some more technical information about the problem).

Regards,
Tim
