### ISSUE TITLE
Link creation does not respect Detail PID

### ISSUE THREAD

**Issue by Enkrod** [lochmueller/calendarize_news#11]
TYPO3 v8.7.24
News v7.2.0
Calendarize v4.1.3
CalendarizeNews v4.1.0

I have a Calendarize List showing Calendarize Events as well as News Events. Details PID points to another page.

This page contains:
1. Calendarize Plugin as Details
2. News Plugin as Details

The links created in the list for calendarize events successfully opens the details page and shows the content.
The links created in the list for news events point to the page the list-plugin is on and not to the details page.

I'm not sure what I am doing wrong here, sorry if this is not an issue but just [PEBKAC](https://de.wiktionary.org/wiki/PEBKAC).

**Comment by lochmueller** [comment]
Hey @Enkrod ,

The calendarize new list genrate the Link via the News ViewHelper: https://github.com/lochmueller/calendarize_news/blob/master/Resources/Private/Partials/News/ListItem.html#L10

This ViewHelper take care of the PID detection: https://github.com/georgringer/news/blob/master/Classes/ViewHelpers/LinkViewHelper.php#L185

I think there is missing News TS configuration in your page e.g. settings -> defaultDetailPid?

Regards,
Tim

**Comment by Enkrod** [comment]
Damn, that actually did the trick. Well that's one day wasted on being stupid.

Thanks.
