### ISSUE TITLE
News do not take on index date properties

### ISSUE THREAD

**Issue by Enkrod** [lochmueller/calendarize_news#12]
Hey Tim, sorry to bother you again.

Without any documentation, I am still very confused about the extension, since I can see there are Xclasses to overwrite the NewsLinkViewhelper and the NewsController->detailAction so the details page should show the date and time from the index, yet it does not.

Also the link to the details page should contain a part `&tx_news_pi1[index]={indexId}` but it doesn't. This makes it seem like the Xclasses are not being used. I can however find them in the autoload_classmap.php

I think I might still have configured something wrong, so here is my step-by-step:

1. Install calendarize
2. Install calendarize_news
3. Include both static templates
4. Create a folder with some news in them and give them calendarize dates
5. Create and configure the plugins on the respective pages. The list of news-indexes is shown correctly by the calendarize plugin and (after configuring the default details pid for tx_news) links correctly to the details page, though both the link and the details page themselves show no influence of the Xclasses.

Am I missing something important? I love the idea behind calendarize and perfer it massively to calendar_base but only calendarize itself has adequate documentation and I am really struggeling to match calendarize_news to my needs.

Grüße aus Hessen, 
Sebastian

**Comment by Enkrod** [comment]
Nevermind.

For everyone stumbling across this Issue in the Future: Look to `EXT:calendarize_news/Resources/Private/News/Detail.html`, switch out the Links in ListItem and build your Detail.html around the now accessible index and index.originalObject. Bam!

**Comment by agendartobias** [comment]
Hey, how did you manage to get ext:news data detail.html template?

**Comment by lochmueller** [comment]
Do you debug with <f:debug>{_all}</f:debug>. You should get a model ono the detail page.

Note: Default of the extension is the link to the detail page of EXT:news. So there is no deep support for missing features if there are missing variables in the detail template.

**Comment by agendartobias** [comment]
hmm, do you have any idea how can i call start and end date from table tx_calendarize_domain_model_index to datail template of ext:news?

**Comment by lochmueller** [comment]
Hmm... there is no good solution for this usecase at the moment. Sorry.
