### ISSUE TITLE
Availability for composer

### ISSUE THREAD

**Issue by TimoWinkler** [lochmueller/calendarize_news#13]
There is currently no 4.1 package available on composer 

The requested package lochmueller/calendarize-news ^4.1 exists as lochmueller/calendarize-news[1.1.0, 1.2.0, 1.3.0, 1.3.1, 2.0.0, dev-master]

I added the constraint dev-master for the time being to add the extension anyway.

**Comment by lochmueller** [comment]
Hey @TimoWinkler 
thanks for the note. There was a hard coded 2.0.0 in the composer.json. I removed the line and release a new version: https://packagist.org/packages/lochmueller/calendarize-news
Regards,
Tim
