### ISSUE TITLE
category selection

### ISSUE THREAD

**Issue by stephangrass** [lochmueller/calendarize_news#2]
I think it was nice, if you a can implement an category selection of existing categories to filter the news-eventlist.

Stephan

**Comment by r4fx** [comment]
any plans to implement this in near future ?

**Comment by lochmueller** [comment]
Hey @r4fx At the moment there are no plans for this feature... I will check all community-issues at the end of october again...

**Comment by r4fx** [comment]
Hi, my friend made some changes in files of "calendarize" extension to achieve category filtering on front-end, I know that those changes should be placed in "calendarize_news". I could send you the code if this will speed up implementation, changes are in 3 files (EventRepository.php, EventSearch.php, IndexRepository.php), or if it is possible please give us a hint where in the code of "calendarize_news" we should place the changes, and then we will provide a pull request for "calendarize_news".

Working example:

![zrzut ekranu 2016-11-03 o 13 47 21](https://cloud.githubusercontent.com/assets/4216415/19966885/0e3f1202-a1ce-11e6-9f3a-e7957e4ee3a2.png)

**Comment by lochmueller** [comment]
Hey @r4fx you cann create a pull request here for the calendarize_news or in the base extension - https://github.com/lochmueller/calendarize - if there are also changes. Please keep in mind, that calendarize has a very general/generic approach. If the changes are related to the news integration, please try to modify calendarize_news only or use hooks/slots of the calendarize extension.
Regards,
Tim

**Comment by lochmueller** [comment]
I drop/close this issue (very old). 
Pull requests are still welcome ;)
