### ISSUE TITLE
Undeclared VH argument with replaceNewsRepositoryByIndexSelection = 0

### ISSUE THREAD

**Issue by okmiim** [lochmueller/calendarize_news#21]
_Note: This is an error I stumbled on while **testing**. For me this has no priority._

1. Set the extensions configuration `basic.replaceNewsRepositoryByIndexSelection = 0` (default)
2. Create a news element with a calendarize configuration
3. Create a calendarize list plugin configured with storagepid, configurationtype,...
4. Open the list view

## Output
```
(1/1) TYPO3Fluid\Fluid\Core\ViewHelper\Exception

Undeclared arguments passed to ViewHelper GeorgRinger\News\ViewHelpers\LinkViewHelper: index. Valid arguments are: additionalAttributes, data, class, dir, id, lang, style, title, accesskey, tabindex, onclick, newsItem, settings, uriOnly, configuration, content, section
in /var/www/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php line 478

at TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->validateAdditionalArguments(array('index' => object(TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\RootNode)))
in /var/www/html/vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php line 586

at TYPO3Fluid\Fluid\Core\Parser\TemplateParser->parseArguments(' newsItem="{news}" index="{index.uid}" class="pull-left"', object(GeorgRinger\News\ViewHelpers\LinkViewHelper))
in /var/www/html/vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php line 353

...
```

## Cause

If `replaceNewsRepositoryByIndexSelection = 0` is set, the Xclass of the LinkViewHelper is not loaded.
In this case the `index` argument of the LinkViewHelper is missing / not defined.
https://github.com/lochmueller/calendarize_news/blob/b7d167a6b9a12b780ed314bb4f3fdd0d8f510037/Resources/Private/Partials/News/ListItem.html#L10

## Versions

- Typo3 10.4.16
- calendarize 10.0.0
- calendarize_news 5.0.0

**Comment by lochmueller** [comment]
Thanks @okmiim I moved the xclass to the right location and overwrite the ViewHelper always...
