### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize_news#22]
I am looking for some information on how to configure the ID of the news detail page to be referenced from the list view.

At the moment the link leads to the calendarize list view page itself. That's not what I want.

Any quick hint somebody? Thx in advance!

**Comment by artus70** [comment]
I already found this (TS):

`plugin.tx_news.settings.detailPid =12`

But can this be set in flexform, too, i.e. by an editor who doesn't have access to web->templates? Or would this be a feature request?

**Comment by lochmueller** [comment]
Hey @artus70 

Good point. It is possible to adapt the FlexForm configuration from EXT:calendarize (in EXT:calendarize_news) and check this separate setting in the news link ViewHelper. Feel free to send a pull request. Otherwise I will check this in the next weeks...

Regards,
Tim
