### ISSUE TITLE
Typo3 11 compatiblity

### ISSUE THREAD

**Issue by shortyxs** [lochmueller/calendarize_news#31]
Will there be a Typo3 11 compatible version of Calendarize News?
Or is it just not tested and I should give it a test drive?

As I am creating a new website I'd really like to go for the all the latest available LTS for the launch.

**Comment by lochmueller** [comment]
Hey @shortyxs ,
there will be a release for v11. But it is not tested currently, and the task has no high priority on my agenda.
Feel free to test this and send a pull request...
Regards,
Tim

**Comment by lochmueller** [comment]
Hey @shortyxs 
I published the current state of the extension to Packagist and TER.
Regards,
Tim
