### ISSUE TITLE
Can't open calendarized news entries in detail view

### ISSUE THREAD

**Issue by miniton** [lochmueller/calendarize_news#42]
News entries that have been calendarized show up in the month, day and list view correctly.
But when I try to open them in the detail view, I get the following error on the detail page: "No Event found! There is no valid fallback PID (list) in the detail plugin".
I can't find a setting for the fallback PID in the plugin.

TYPO3 11.5.27
calendarize 12.4.4
calendarize_news 7.0.0

**Comment by miniton** [comment]
Update: I guess I found the fallback: When I set [settings.listPid] in the plugin, there is no error message, but the site falls back to this page, when I try to open the details.

And the problem does not only appear with calendarized news entries, but also when a news entry and an calendarize event have the same URL segment (slug).

**Comment by miniton** [comment]
Hey @lochmueller,

there are no entries with the same slug in the index, only a news record with the same slug. But I guess you are right, that is not the problem. The problem seems to be that the detail plugin ignores the News Events.

My news events are stored in 237, my calendarize events in 463. Both record storages are set correctly in the detail plugin. Also both data types (Calendarize Event, News Event).

If I create an calendarize event in the news folder 237 it works. If I create a news event in folder 463 it doesn't work in the detail plugin.

Everything works in the month and day view, which are used on the site.

Cheers
Christian








TYPO3 11.5.27
calendarize 12.4.4
calendarize_news 7.0.0

**Comment by lochmueller** [comment]
Hey @miniton 

Sound strange. Please keep in mind, that EXT:calendarize_news has no Detail page rendering for the news records. The ListView point to the EXT:news detail plugin. Perhaps this is the misunderstanding? Please use EXT:news to render the News record and the calendar plugin link to this newsPid.
If EXT:calendarize should render the detail page, you have to overwrite the Detail and List Template for your requirements.

Regards,
Tim

**Comment by lochmueller** [comment]
Also close this issue, because it is very old....
