### ISSUE TITLE
Can you create new release (from master) with support for news 11 (and 10)?

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize_news#44]
**latest release 7.0.0:** composer.json

```
"lochmueller/calendarize": "^10.0||^11.0||^12.0",
"georgringer/news": "^8.5||^9.0"
```

https://github.com/lochmueller/calendarize_news/blob/7.0.0/composer.json

**master**: composer.json

"lochmueller/calendarize": "^10.0||^11.0||^12.0",
"georgringer/news": "^8.5||^9.0||^10.0||^11.0"

https://github.com/lochmueller/calendarize_news/blob/master/composer.json

We have been using this for some time with no problems:

```
"georgringer/news": "^11.1.2",
"lochmueller/calendarize": "^12.4.4",
"lochmueller/calendarize-news": "dev-master"
```,

**Comment by lochmueller** [comment]
Hey @sypets 
Thanks for your feedback. I pushed Version 7.1.0 to Packagist a few moments ago: https://packagist.org/packages/lochmueller/calendarize-news
Regards,
Tim
