### ISSUE TITLE
Taking categories assigned to news-entries into account in views  ("month" etc.)?

### ISSUE THREAD

**Issue by micha68g** [lochmueller/calendarize_news#45]
Hi,

is there any chance, that the different views (year/month...) could take into account a category assigned to **_a news-entry_**.
If I assign a category to a "real" calendarize-event, the category-filtered list-views work as expected. But If I assign the same category to a calendarize-entry with a news-entry (via "Extended"-Tab) the entry it's not showing up in the calendarize-listview limited to this special category.

Everything fine with non-categorized items, either calendarize-items or news-items.

Thanks for infos
Michael

**Comment by okmiim** [comment]
Hi @micha68g,

in the upcoming calendarize 13 version (TYPO3 v12) this will be supported out of the box.
However, I don't think this will be added to older versions. You may want to implement it for yourself.

---

To enable this for a older versions (calendarize 12; TYPO3 v10/v11) a specific EventListener needs to be implemented,
Steps to implement (e.g. in your own sitepacke):

1. Copy the class [DefaultEventConstraintsListener.php](https://github.com/lochmueller/calendarize/blob/f310e23e54391ae0f3a6102593df3e34e764f6ff/Classes/EventListener/DefaultEventConstraintsListener.php) to an extension (e.g. your sitepackage)
     1. Change classname and namespace
     2. Change the return value of `getTableName` to `'tx_news_domain_model_news'`
     3. Replace `Register::UNIQUE_REGISTER_KEY` with `'Event'`
2. Register your [event listener (TYPO3 guide)](https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/HowTo/Events/Index.html), similar to this
    https://github.com/lochmueller/calendarize/blob/f310e23e54391ae0f3a6102593df3e34e764f6ff/Configuration/Services.yaml#L47-L51

Regards

**Comment by lochmueller** [comment]
I close this issue. Will not be added to old versions.... Thanks okmiim for the explanation.
