### ISSUE TITLE
Listview restriction / replaceNewsRepositoryByIndexSelection

### ISSUE THREAD

**Issue by saneinsane** [lochmueller/calendarize_news#6]
With replaceNewsRepositoryByIndexSelection enabled how can I control a list view containing news records with multiple index entries? 
Flexform fields timeRestriction,timeRestrictionHigh and limit seem not to work here.

**Comment by saneinsane** [comment]
Limit settings works when I include the list by TS; so this might be a configuration issue - please close.

**Comment by lochmueller** [comment]
Ok. Thanks for rechecking this...
