### ISSUE TITLE
Option: manual sorting in pugin.tx_news gone, when calendarize_news is installed

### ISSUE THREAD

**Issue by sdesign6** [lochmueller/calendarize_news#8]
When calendarize_news is installed, the tx_news option "Manual Sorting" records.manualSorting (boolesch) is not working anymore. No choice to set it in the plugin settings, overwritten by calendarize_news.

ext.table.php line 17 in calendarize_news: $configuration->getManualSorting() is not recognized
$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['orderByNews'] = 'tstamp,datetime,crdate,title,calendarize';

ext.table.php line 78 in news
$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['orderByNews'] = 'tstamp,datetime,crdate,title' . ($configuration->getManualSorting() ? ',sorting' : '');

**Comment by lochmueller** [comment]
Thanks for the hint. The "calendarize" field is "added" now. So the complete list is not changed and the list is based on the News extension (incl. sorting if enable).

Regards,
Tim
