### ISSUE TITLE
Compatibility with TYPO3 version 9.5.x and EXT:news 7.x

### ISSUE THREAD

**Issue by angeloprevitali** [lochmueller/calendarize_news#9]
Hi Tim

are there any plans to adapt your extension EXT:calendarize_news with the actual TYPO3 CMS verson 9.5.x with the actual EXT:news 7.x

Thanks for your feedback.

Best regards,
Angelo

**Comment by lochmueller** [comment]
Hey @angeloprevitali 
release 4.1.0 is on the way to TER.
Regards,
Tim
